### ISSUE TITLE
Data corruption when reading PCAP file, probably related to IPv6 fragment header

### ISSUE THREAD

**Issue by ZbynekZ** [chmorgan/packetnet#104]
I get corrupted data when reading a PCAP file that contains a packet with IPv6 fragment header.

Repro code:

```
    class Program
    {
        static void Main(string[] args)
        {
            var captureDevice = new CaptureFileReaderDevice("test2.pcap");
            captureDevice.OnPacketArrival += captureDevice_OnPacketArrival;
            captureDevice.StartCapture();
        }

        static void captureDevice_OnPacketArrival(object sender, CaptureEventArgs captureEventArgs)
        {
            RawCapture rawCapture = captureEventArgs.Packet;

            // The assertions below test against the correct data - and they pass.
            Debug.Assert(rawCapture.Data[66] == 0);
            Debug.Assert(rawCapture.Data[67] == 0);
            
            Packet packet = Packet.ParsePacket(LinkLayers.Ethernet, rawCapture.Data);

            // The line below, or any further dissecting of the packet, triggers the corruption.
            byte[] bytes = packet.Bytes;

            // The assertions below test against the correct data - and they now fail.
            Debug.Assert(rawCapture.Data[66] == 0);
            Debug.Assert(rawCapture.Data[67] == 0);

            // Cannot really dissect any packets with fragment header for IPv6 - the data gets corrupted.
        }

```

PCAP file (zipped) - it has just one packet in it: 
[test2.zip](https://github.com/chmorgan/packetnet/files/3802034/test2.zip)

As it can be verified e.g. in Wireshark or by viewing the PCAP file in hex editor, there should be zeros in two bytes close to the beginning of this 2nd fragment of UDP payload (offsets are 4, 5 in this fragment of the UDP payload). And indeed, the raw capture initially has the zeros. But I cannot work with raw capture - I want to dissect it. After Packet.ParsePacket however, accessing the Packet.Bytes or further dissecting the packets modifies the raw capture - and anything derived from it becomes immediately corrupted as well. The second set of assertions in the code shows how the bytes inside the payload have changed from zero to non-zero.

**Comment by Phyxion** [comment]
The first problem is that the extension headers (including a fragment header) are not added to bytes at all because it's not seen as a header or payload. These should've be added to the header (as extension headers are of course part of the header). The next problem is that several bytes are being overriden, namely the bytes at index 67, 68, 75 and 76. This happens because the captured packet was detected as UDP payload, which was mostly OK, but it was a fragmented part, so this shouldn't have been parsed as an UDP packet. As calling .Bytes updates the calculated values (including the length), these bytes were overwritten.

Keep in mind that packetnet always uses and overwrites the original data (the passed in byte array) for performance reasons. If you don't want that, copy the byte array first.

**Comment by ZbynekZ** [comment]
That looks great - thank you.
Will there be a new version of the NuGet package published? Because that's what I and my users depend on...

**Comment by Phyxion** [comment]
Yes, might do #102 before NuGet push though, so please give it a try first.

**Comment by ZbynekZ** [comment]
Understood - no hurry - but see my comment in #102 too.
